version: '3.4'

services:
  spot:
    image: spot
    networks:
      - db-net
    ports:
      - '8008:8000'
    build:
      context: .
      dockerfile: ./Dockerfile

  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3308:3306'
    restart: always
    volumes:
      - db-spot:/var/lib/mysql
    env_file: .env
    networks:
      - db-net

volumes:
  db-spot:
networks:
  db-net: